Config = Config or {}

Config.openKeyBind = 'I' -- https://docs.fivem.net/docs/game-references/input-mapper-parameter-ids/
Config.showFastSlotsKeyBind = 'TAB' -- Key to show fast slots preview

Config.dataBaseType = 'mongodb' -- 'mysql' or 'mongodb'
Config.dataBaseName = 'mongodb' -- Name of the database resource (only in case of mongodb)

Config.backEngines = { -- list of vehicles that has engine in the back (not all, you can add more)
    [`ninef`] = true,
    [`adder`] = true,
    [`vagner`] = true,
    [`t20`] = true,
    [`infernus`] = true,
    [`zentorno`] = true,
    [`reaper`] = true,
    [`comet2`] = true,
    [`comet3`] = true,
    [`jester`] = true,
    [`jester2`] = true,
    [`cheetah`] = true,
    [`cheetah2`] = true,
    [`prototipo`] = true,
    [`turismor`] = true,
    [`pfister811`] = true,
    [`ardent`] = true,
    [`nero`] = true,
    [`nero2`] = true,
    [`tempesta`] = true,
    [`vacca`] = true,
    [`bullet`] = true,
    [`osiris`] = true,
    [`entityxf`] = true,
    [`turismo2`] = true,
    [`fmj`] = true,
    [`re7b`] = true,
    [`tyrus`] = true,
    [`italigtb`] = true,
    [`penetrator`] = true,
    [`monroe`] = true,
    [`ninef2`] = true,
    [`stingergt`] = true,
    [`surfer`] = true,
    [`surfer2`] = true,
    [`gp1`] = true,
    [`autarch`] = true,
    [`tyrant`] = true,
    [`coquette4`] = true,
}